
const ADD_TO_LIST = 'ADD_TO_LIST';
const ADD_TO_CART = 'ADD_TO_CART';
const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const DELETE_FROM_CART = 'DELETE_FROM_CART';
const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
const DELETE_FROM_LIST = 'DELETE_FROM_LIST';

export {
  ADD_TO_LIST,
  ADD_TO_CART,
  ADD_TO_FAVORITES,
  DELETE_FROM_CART,
  DELETE_FROM_FAVORITES,
  DELETE_FROM_LIST,
};